Parameter to override a field type on a per-language basis
1Password/typeshare pull request #119
Opened 2023-05-19 00:40 UTC by InquisitivePenguin

Resolves #22.

There is now a field decorator that can override the type of the field in the generated language(s) of your choice. This override takes precedent over everything else, including type mapping.

2023-05-19 00:40 UTC, InquisitivePenguin commented
This PR depends on #118.

2023-05-25 23:30 UTC, Lucretiel commented
General questions:

- Is this the first `typeshare` attribute (aside from the top-level one)?
- Is there an assumption here that the types should be compatible without any additional (de)serialize logic, in either direction, in either rust or the target language?

2023-05-25 23:30 UTC, Lucretiel requested changes

2023-05-25 23:30 UTC, Lucretiel commented on core/data/tests/can_override_types/input.rs
> +    #[typeshare(swift(type = "Int"), typescript(readonly, type = "any | undefined"), kotlin(type = "Int"), go(type = "uint"), scala(type = "Short"))]
Nit: recommend splitting these up over multiple lines

2023-05-26 00:04 UTC, InquisitivePenguin commented
> General questions:
> 
>     * Is this the first `typeshare` attribute (aside from the top-level one)?
> 
>     * Is there an assumption here that the types should be compatible without any additional (de)serialize logic, in either direction, in either rust or the target language?

* No, we already have field decorators like `#[typeshare(typescript(readonly))]`.
* Correct, we don't check for compatibility. That's the responsibility of the end-user (given that this is _usually_ a last-resort option)

2023-06-17 00:23 UTC, Lucretiel approved these changes

2023-06-17 01:00 UTC, Lucretiel commented
Slightly screwed up merging #118 so I force-rebased this branch. Merge should be fine.

2023-06-17 01:02 UTC, merged