Support char type
1Password/typeshare pull request #128
Opened 2023-06-19 19:28 UTC by czocher

Add support for the Rust `char` type.

Closes #103

2023-06-24 00:34 UTC, Lucretiel commented
Looks great, just a small Swift nit and it's good to merge

2023-06-24 10:27 UTC, czocher commented
@Lucretiel already fixed ;).

2023-06-29 01:59 UTC, Lucretiel commented
I'm not seeing it on the PR; does it need to be pushed?

2023-06-29 04:19 UTC, czocher commented
> I'm not seeing it on the PR; does it need to be pushed?

@Lucretiel You mean the change requested by @CerulanLumina? I amended the change just after they noticed it. This is the current version that shows up when I check the changes in this PR: https://github.com/1Password/typeshare/pull/128/files#diff-e3f812823b9b43de87bbd7c54ab61d3e102c387d74245c65cd8a0e3bbca2193e, is there some other thing I missed?

2023-07-01 00:39 UTC, Lucretiel commented
Whoops, it was *I* who didn't didn't press Push on my review and just let it sit as a draft

2023-07-01 00:39 UTC, Lucretiel requested changes

2023-07-01 10:17 UTC, czocher commented on core/src/language/swift.rs
> +            SpecialRustType::Char => "UnicodeScalar".into(),
Thanks!

2023-07-01 10:19 UTC, czocher commented
@Lucretiel done!

2023-07-07 21:07 UTC, CerulanLumina commented
Looks good! Just need the commit to pass signing then we'll merge!

2023-07-07 22:58 UTC, Lucretiel approved these changes

2023-07-08 12:46 UTC, czocher commented
There was some weird mixup with my GitHub account configuration, reuploaded my GPG key and it seems to work. Thanks!

2023-07-13 16:07 UTC, merged